name: Hugo Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            HUGO_VERSION: 0.128.0
        steps:
            - name: Install Hugo CLI
              run: |
                  wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
                  && sudo dpkg -i ${{ runner.temp }}/hugo.deb
            - uses: actions/checkout@v4
            - name: Build Hugo Site (panic on warning)
              run: |
                  touch hugo.minimal-config.yaml
                  echo "params:" >> hugo.minimal-config.yaml
                  echo "  themes:" >> hugo.minimal-config.yaml
                  echo "    event:" >> hugo.minimal-config.yaml
                  echo "      sessionizeId: test" >> hugo.minimal-config.yaml

                  hugo --printI18nWarnings --printMemoryUsage --printPathWarnings --config hugo.minimal-config.yaml --panicOnWarning
